# Standardize the Units

In [1]:
import os
from pathlib import Path

import pandas as pd

In [2]:
path_to_data = Path(os.getcwd()).parents[1] / "data" 
path_to_recipes = path_to_data / "input" / "3_standardize_the_data" / "parsed_recipes.json"

In [3]:
df = pd.read_json(path_to_recipes)
df.head()

,serving_size,preparation_time,cooking_time,ingredients,steps,title,date,tags,introduction,ingredients_source_text,directions_source_text
0,4.0,None,None,"[{'id': 1, 'name': 'potatoes', 'quantity': 1.0...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
1,7.0,12.0,None,"[{'id': 1, 'name': 'salt pork', 'quantity': 0....","[{'number': 1, 'description': 'Mince the garli...",Red Sauce (Ragu all'Italiana),2021-03-16,"[italian, sauce]",My great-grandma's red sauce. All purpose: goo...,- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and..."
2,1.0,20.0,10.0,"[{'id': 1, 'name': 'wheat flour', 'quantity': ...","[{'number': 1, 'description': 'Mix all ingredi...",Pancake,2021-03-11,"[quick, breakfast, sweet, pancake, cheesefare]",![Pancakes made at home](/pix/pancake.webp) - ...,- 200g wheat flour or 100g glutenfree flour - ...,1. Mix all ingredients in a bowl. 2. Let the d...
3,2.0,10.0,15.0,"[{'id': 1, 'name': 'water', 'quantity': 2.0, '...","[{'number': 1, 'description': 'Whisk water, co...",Teriyaki Beef Wok,2022-08-20,"[beef, asian, noodles]",![Teriyaki Beef Wok](/pix/teriyaki-beef.webp) ...,- 2 dL water - 2 tbsp cornstarch - 1 tbsp hone...,"1. Whisk water, cornstarch, honey, ginger and ..."
4,4.0,15.0,"{'min': 20.0, 'max': 30.0}","[{'id': 1, 'name': 'pasta', 'quantity': 500.0,...","[{'number': 1, 'description': 'Boil water and ...","Baked pasta with broccoli, boiled eggs and sca...",2021-04-15,"[italian, pasta, broccoli, cheesefare]",![baked-pasta-with-broccoli](/pix/baked-pasta-...,- 500g pasta - 500g broccoli - 4 eggs - 200g s...,1. Boil water and add salt (a handful for ever...

In [4]:
# Creating a ID for the recipe

df.reset_index(inplace=True)
df.rename(columns={"index":"id"}, inplace=True)
df.head()

,id,serving_size,preparation_time,cooking_time,ingredients,steps,title,date,tags,introduction,ingredients_source_text,directions_source_text
0,0,4.0,None,None,"[{'id': 1, 'name': 'potatoes', 'quantity': 1.0...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
1,1,7.0,12.0,None,"[{'id': 1, 'name': 'salt pork', 'quantity': 0....","[{'number': 1, 'description': 'Mince the garli...",Red Sauce (Ragu all'Italiana),2021-03-16,"[italian, sauce]",My great-grandma's red sauce. All purpose: goo...,- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and..."
2,2,1.0,20.0,10.0,"[{'id': 1, 'name': 'wheat flour', 'quantity': ...","[{'number': 1, 'description': 'Mix all ingredi...",Pancake,2021-03-11,"[quick, breakfast, sweet, pancake, cheesefare]",![Pancakes made at home](/pix/pancake.webp) - ...,- 200g wheat flour or 100g glutenfree flour - ...,1. Mix all ingredients in a bowl. 2. Let the d...
3,3,2.0,10.0,15.0,"[{'id': 1, 'name': 'water', 'quantity': 2.0, '...","[{'number': 1, 'description': 'Whisk water, co...",Teriyaki Beef Wok,2022-08-20,"[beef, asian, noodles]",![Teriyaki Beef Wok](/pix/teriyaki-beef.webp) ...,- 2 dL water - 2 tbsp cornstarch - 1 tbsp hone...,"1. Whisk water, cornstarch, honey, ginger and ..."
4,4,4.0,15.0,"{'min': 20.0, 'max': 30.0}","[{'id': 1, 'name': 'pasta', 'quantity': 500.0,...","[{'number': 1, 'description': 'Boil water and ...","Baked pasta with broccoli, boiled eggs and sca...",2021-04-15,"[italian, pasta, broccoli, cheesefare]",![baked-pasta-with-broccoli](/pix/baked-pasta-...,- 500g pasta - 500g broccoli - 4 eggs - 200g s...,1. Boil water and add salt (a handful for ever...

In [5]:
_df = df.copy(deep=True)

In [6]:
_df.shape

(360, 12)

## Exploring the ingredients

In [7]:
df = _df.explode("ingredients")
df.head()

,id,serving_size,preparation_time,cooking_time,ingredients,steps,title,date,tags,introduction,ingredients_source_text,directions_source_text
0,0,4.0,None,None,"{'id': 1, 'name': 'potatoes', 'quantity': 1.0,...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
0,0,4.0,None,None,"{'id': 2, 'name': 'milk', 'quantity': 200.0, '...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
0,0,4.0,None,None,"{'id': 3, 'name': 'mayonnaise', 'quantity': 20...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
0,0,4.0,None,None,"{'id': 4, 'name': 'cheese', 'quantity': 100.0,...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
0,0,4.0,None,None,"{'id': 5, 'name': 'garlic powder', 'quantity':...","[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...

In [8]:
dfi = pd.json_normalize(df["ingredients"])
dfi.head()

   id           name  quantity      unit  optional  quantity.min  quantity.max
0   1       potatoes       1.0  kilogram     False           NaN           NaN
1   2           milk     200.0        ml     False           NaN           NaN
2   3     mayonnaise     200.0        ml     False           NaN           NaN
3   4         cheese     100.0      gram      True           NaN           NaN
4   5  garlic powder       NaN      None      True           NaN           NaN

In [9]:
dfi.columns = map(lambda v:f"ingredients.{v}", dfi.columns)
dfi.head()

,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max
0,1,potatoes,1.0,kilogram,False,NaN,NaN
1,2,milk,200.0,ml,False,NaN,NaN
2,3,mayonnaise,200.0,ml,False,NaN,NaN
3,4,cheese,100.0,gram,True,NaN,NaN
4,5,garlic powder,NaN,None,True,NaN,NaN

In [10]:
df:pd.DataFrame = df.drop("ingredients", axis=1).reset_index(drop=True).join(dfi)
df.head()

,id,serving_size,preparation_time,cooking_time,steps,title,date,tags,introduction,ingredients_source_text,directions_source_text,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max
0,0,4.0,None,None,"[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,1,potatoes,1.0,kilogram,False,NaN,NaN
1,0,4.0,None,None,"[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,2,milk,200.0,ml,False,NaN,NaN
2,0,4.0,None,None,"[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,3,mayonnaise,200.0,ml,False,NaN,NaN
3,0,4.0,None,None,"[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,4,cheese,100.0,gram,True,NaN,NaN
4,0,4.0,None,None,"[{'number': 1, 'description': 'Peel and cut th...",Creamy Mashed Potatoes,2021-03-12,"[potato, side, cheesefare]",![Creamy Mashed Potatoes](/pix/creamy-mashed-p...,The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,5,garlic powder,NaN,None,True,NaN,NaN

In [11]:
df.shape

(3105, 18)

In [12]:
df.columns

Index(['id', 'serving_size', 'preparation_time', 'cooking_time', 'steps',
       'title', 'date', 'tags', 'introduction', 'ingredients_source_text',
       'directions_source_text', 'ingredients.id', 'ingredients.name',
       'ingredients.quantity', 'ingredients.unit', 'ingredients.optional',
       'ingredients.quantity.min', 'ingredients.quantity.max'],
      dtype='object')

In [13]:
# Reorder columns
new_column_order = [
    "id",
    "title",
    "serving_size",
    "preparation_time",
    "cooking_time",
    "ingredients.id", 
    "ingredients.name",
    "ingredients.quantity", 
    "ingredients.unit", 
    "ingredients.optional",
    "ingredients.quantity.min", 
    "ingredients.quantity.max",
    "date",
    "tags",
    "steps",
    "ingredients_source_text",
    "directions_source_text"

]

df = df[new_column_order]

In [14]:
df["ingredients.unit"].unique().tolist()

['kilogram',
 'ml',
 'gram',
 None,
 'strip',
 'unit',
 'pound',
 'clove',
 'N/A',
 'tablespoon',
 'ounce',
 'teaspoon',
 'dl',
 'cup',
 'can',
 'sprig',
 'slice',
 'dash',
 'milliliter',
 'bunch',
 'splash',
 'handful',
 'head',
 'block',
 'stick',
 'unknown',
 'g',
 'leaf',
 'pinch',
 'bowl',
 'mug',
 'pint',
 'spoon',
 'package',
 'liter',
 'inch',
 'glass',
 'jar',
 'centiliter',
 'twig',
 'sheet',
 'piece',
 'rib',
 'cube',
 'handfull',
 'bottle',
 'serving',
 'fluid_ounce',
 'recipe',
 'cm',
 'container',
 'bag',
 'shot',
 'loaf',
 'envelope',
 'l',
 'medium',
 'large',
 'whole',
 'small',
 'percent',
 'pod',
 'fillet',
 'cl',
 'box',
 'quart',
 'strand',
 'stalk',
 'fruit']

Some units have unexpecte values like None or nan. We will explore the ingredients to see what we can do to standardize the units.
In particular, we need to check if this is a LLM parsing problem or if the issue occured during post-processing.

In [15]:
pd.set_option("display.max_colwidth",None)

In [16]:
ingredients_without_unit = df[df["ingredients.unit"].isna()][["id", "title", "ingredients.name", "ingredients.quantity", "ingredients.unit", "ingredients.optional", "ingredients_source_text"]]
ingredients_without_unit

,id,title,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients_source_text
4,0,Creamy Mashed Potatoes,garlic powder,NaN,None,True,"The quantities here are for about four adult portions. If you are planning on eating this as a side dish, it might be more like 6-8 portions. * 1kg potatoes * 200ml milk* * 200ml mayonnaise* * ~100g cheese * Garlic powder * 12-16 strips of bacon * Butter * 3-4 green onions * Black pepper * Salt *You can play with the proportions depending on how creamy or dry you want the mashed potatoes to be."
6,0,Creamy Mashed Potatoes,butter,NaN,None,True,"The quantities here are for about four adult portions. If you are planning on eating this as a side dish, it might be more like 6-8 portions. * 1kg potatoes * 200ml milk* * 200ml mayonnaise* * ~100g cheese * Garlic powder * 12-16 strips of bacon * Butter * 3-4 green onions * Black pepper * Salt *You can play with the proportions depending on how creamy or dry you want the mashed potatoes to be."
8,0,Creamy Mashed Potatoes,black pepper,NaN,None,True,"The quantities here are for about four adult portions. If you are planning on eating this as a side dish, it might be more like 6-8 portions. * 1kg potatoes * 200ml milk* * 200ml mayonnaise* * ~100g cheese * Garlic powder * 12-16 strips of bacon * Butter * 3-4 green onions * Black pepper * Salt *You can play with the proportions depending on how creamy or dry you want the mashed potatoes to be."
9,0,Creamy Mashed Potatoes,salt,NaN,None,True,"The quantities here are for about four adult portions. If you are planning on eating this as a side dish, it might be more like 6-8 portions. * 1kg potatoes * 200ml milk* * 200ml mayonnaise* * ~100g cheese * Garlic powder * 12-16 strips of bacon * Butter * 3-4 green onions * Black pepper * Salt *You can play with the proportions depending on how creamy or dry you want the mashed potatoes to be."
33,3,Teriyaki Beef Wok,sesame oil,NaN,None,False,"- 2 dL water - 2 tbsp cornstarch - 1 tbsp honey - 1/4 tsp ginger - 3 tbsp soy sauce - Sesame oil - Beef slices or strips - Carrot, sliced (optional) - Broccoli, florets (optional) - Baby corn (optional) - Water chestnut, sliced (optional) - Bean sprouts (optional) - Chili pepper, diced (optional) - Noodles or rice"
...,...,...,...,...,...,...,...
2941,338,Pilaf,cumin,NaN,None,True,"- 150ml cooking oil - 1kg long grain [rice](/rice) - 1.5kg meat (lamb or any other kind of meat) - 500g onions - 500g carrots - 2 tbsp salt - 5 cloves of garlic - raisins, cardamom, paprika, coriander, cinnamon, cumin, turmeric (all optional)"
2942,338,Pilaf,turmeric,NaN,None,True,"- 150ml cooking oil - 1kg long grain [rice](/rice) - 1.5kg meat (lamb or any other kind of meat) - 500g onions - 500g carrots - 2 tbsp salt - 5 cloves of garlic - raisins, cardamom, paprika, coriander, cinnamon, cumin, turmeric (all optional)"
3035,349,Italian Bread,all-purpose flour,NaN,None,True,- 600g or 5 cups bread flour (or all-purpose if not available) - 1 packet (appr. 2 1/4 tsp or 7g) active dry yeast - olive oil for greasing
3037,349,Italian Bread,olive oil,NaN,None,True,- 600g or 5 cups bread flour (or all-purpose if not available) - 1 packet (appr. 2 1/4 tsp or 7g) active dry yeast - olive oil for greasing
3063,352,Pepper Sauce,salt,NaN,None,True,"- 1 tablespoon freshy ground rose pepper, green pepper and black pepper - 1 teaspoon dijon mustard - 1dl bouillon - 2dl cream - Salt if needed"

It looks like the ingredients without unit are mainly ingredients whose unit were not present in the original recipe. 
Moreover, it looks like it's mainly optional spicies

In [17]:
ingredients_without_unit["id"].value_counts()

id
236    15
249    13
127    10
3       9
160     9
       ..
146     1
96      1
110     1
134     1
352     1
Name: count, Length: 69, dtype: int64

"Only" 69 recipes are concerned by this issue.
Might be worth considering dropping those recipes

In [18]:
ingredients_without_unit.shape

(239, 7)

In [19]:
ingredients_without_unit[~ingredients_without_unit["ingredients.optional"]]

,id,title,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients_source_text
33,3,Teriyaki Beef Wok,sesame oil,NaN,None,False,"- 2 dL water - 2 tbsp cornstarch - 1 tbsp honey - 1/4 tsp ginger - 3 tbsp soy sauce - Sesame oil - Beef slices or strips - Carrot, sliced (optional) - Broccoli, florets (optional) - Baby corn (optional) - Water chestnut, sliced (optional) - Bean sprouts (optional) - Chili pepper, diced (optional) - Noodles or rice"
34,3,Teriyaki Beef Wok,beef slices or strips,NaN,None,False,"- 2 dL water - 2 tbsp cornstarch - 1 tbsp honey - 1/4 tsp ginger - 3 tbsp soy sauce - Sesame oil - Beef slices or strips - Carrot, sliced (optional) - Broccoli, florets (optional) - Baby corn (optional) - Water chestnut, sliced (optional) - Bean sprouts (optional) - Chili pepper, diced (optional) - Noodles or rice"
41,3,Teriyaki Beef Wok,noodles or rice,NaN,None,False,"- 2 dL water - 2 tbsp cornstarch - 1 tbsp honey - 1/4 tsp ginger - 3 tbsp soy sauce - Sesame oil - Beef slices or strips - Carrot, sliced (optional) - Broccoli, florets (optional) - Baby corn (optional) - Water chestnut, sliced (optional) - Bean sprouts (optional) - Chili pepper, diced (optional) - Noodles or rice"
68,6,Frijol con puerco,Mexican tortillas,NaN,None,False,"- **1 kg of black beans**, rinsed and drained. - **2 kg** of pork loin or ribs cut into **5 cm** pieces, it can be mixture of the two. - **1 white onion** without skin cut, in half. - **4 branches of fresh _epazote_**, or **15 branches of coriander** tied with kitchen twine. - **8 to 10 radishes**, julienned or striped. - **1 cup of chopped cilantro**. - **1 Mexican avocado**, halved, pitted, pulp cut into squares. - **4 lemons**, quartered. - **Yucatan style tomato sauce** or _Chiltomate_ to taste (**optional**) - **Mexican tortillas**"
120,11,Ragu Napoletano,dry oregano,NaN,None,False,"### Tomato Sauce - 6-10 lbs San Marzano plum tomatoes (fresh or canned peeled) - Tomato paste (optional) ### Aromatics and Herbs - 8 cloves garlic - 1.5 white onions - 6-8 oz red wine - 8 fresh basil leaves - Dry oregano - Red pepper ### Meat - 1-2 lb pork tenderloin - 1-2 lb sweet and or spicy Italian sausage - 1 lb cubed stewing beef (chuck, short rib, or oxtail) ### Meatballs - 1-2 lb total of ground beef chuck, veal, and pork - 1 1/2 cups grated Pecorino Romano cheese - 1 1/2 cups breadcrumbs (baked stale bread, oregano, salt and pepper pulsed in a food processor) - 2-3 eggs - Splash of milk - Handfull of fresh parsley chopped - Sprig of fresh basil chopped - 1/2 onion minced - 4-8 cloves garlic minced"
...,...,...,...,...,...,...,...
2404,273,Russian 1000 Islands Sauce,Worchestershire sauce,NaN,None,False,- Ketchup (Sir Kensington's recommended) - Mayonnaise - Horseradish - Worchestershire sauce - Paprika - Dijon mustard - Onion powder - Pickle relish (optional)
2405,273,Russian 1000 Islands Sauce,Paprika,NaN,None,False,- Ketchup (Sir Kensington's recommended) - Mayonnaise - Horseradish - Worchestershire sauce - Paprika - Dijon mustard - Onion powder - Pickle relish (optional)
2406,273,Russian 1000 Islands Sauce,Dijon mustard,NaN,None,False,- Ketchup (Sir Kensington's recommended) - Mayonnaise - Horseradish - Worchestershire sauce - Paprika - Dijon mustard - Onion powder - Pickle relish (optional)
2407,273,Russian 1000 Islands Sauce,Onion powder,NaN,None,False,- Ketchup (Sir Kensington's recommended) - Mayonnaise - Horseradish - Worchestershire sauce - Paprika - Dijon mustard - Onion powder - Pickle relish (optional)
2797,320,Mexican Meat Loaf,Cooking Spray,NaN,None,False,"- 1 lb Lean Ground Beef - 1 cup Black Beans (canned), rinsed and drained - 1 cup Salsa, divided - 1/2 cup Corn (frozen) - 1/2 cup Bread Crumbs - Cooking Spray"

My assumption around the ingredients without unit being mainly optional spices is wrong.
However, it is correct to say the unit is missing when it was already missing in the original dataset

In [20]:
ingredients_without_unit[ingredients_without_unit["id"].isin([236,249])]

,id,title,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients_source_text
2049,236,Francesinha,bread,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2050,236,Francesinha,linguiça,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2051,236,Francesinha,ham,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2052,236,Francesinha,Portuguese cheese,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2053,236,Francesinha,beef meat,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2054,236,Francesinha,blonde beer,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2055,236,Francesinha,fried tomato sauce,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2056,236,Francesinha,port wine,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2057,236,Francesinha,beef broth,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2058,236,Francesinha,salted butter,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2059,236,Francesinha,onion,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2060,236,Francesinha,minced garlic,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2061,236,Francesinha,cornstarch,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2062,236,Francesinha,olive oil,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2063,236,Francesinha,piripiri,NaN,None,False,### Based Ingredients - bread - linguiça (type of Portuguese sausage) - ham - Portuguese cheese - beef meat ### Sauce Ingredients - blonde beer - fried tomato sauce - port wine - beef broth - salted butter - onion - minced garlic - cornstarch - olive oil - piripiri (Portuguese chili)
2166,249,Broiled Trevally,giant trevally,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2167,249,Broiled Trevally,eggplants,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2168,249,Broiled Trevally,squash,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2169,249,Broiled Trevally,carrots,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2170,249,Broiled Trevally,onion,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2171,249,Broiled Trevally,garlic,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2172,249,Broiled Trevally,ginger,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2173,249,Broiled Trevally,tomatoes,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2174,249,Broiled Trevally,bay leaf,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2175,249,Broiled Trevally,olive oil,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2176,249,Broiled Trevally,thyme,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2177,249,Broiled Trevally,basil,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter
2178,249,Broiled Trevally,butter,NaN,None,False,- giant trevally - eggplants - squash (or zucchini) - carrots - onion - garlic - ginger - tomatoes - bay leaf - olive oil - thyme - basil - butter

In [21]:
ingredients_with_na_unit = df[df["ingredients.unit"] == "N/A"][["id", "title", "ingredients.name", "ingredients.quantity", "ingredients.unit", "ingredients.optional", "ingredients_source_text"]]
ingredients_with_na_unit

,id,title,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients_source_text
13,1,Red Sauce (Ragu all'Italiana),Crushed hot red pepper,NaN,N/A,True,- 1/3 lb salt pork - 2 lb chuck roast - 3 Cloves of garlic - Crushed hot red pepper - Sweet onion - Large carrot - 2 Bay leaves - 2 tbsp. Olive oil (she used mazola oil) - 12 oz. Can tomato paste - 29 oz. Diced tomatoes - 29 oz. Tomato puree
27,2,Pancake,salt,NaN,N/A,False,- 200g wheat flour or 100g glutenfree flour - 200 ml milk - 2 eggs - 2 tsp sugar - 1 tsp baking soda - a little bit of salt
70,7,Beef Wellington,Extra Virgin Olive Oil,NaN,N/A,False,"- 1lb of **Fillet** Beef - Extra Virgin Olive Oil - 1lb of mushrooms - 4 Thinly Cut Slices of Ham - 2tbsp of Yellow Mustard - 7oz of Puff Pastry - 2 Egg Yolks Beaten Side note: Fillet beef is preferred. It gives the beef wellington a soft, tender and juicy flavour. Trust me, using fillet is worth it."
103,9,Ragù,Parmesan cheese,NaN,N/A,True,"- 1 pound tubular dried pasta - 1 pound sweet Italian sausage - 1 onion, minced - 1 carrot, minced - 1 celery stalk, minced - 28oz (825 ml) can of whole tomatoes - 3 tablespoon of tomato paste - 1/4 cup fresh parsley - 1 sprig of fresh thyme - 1 sprig of fresh rosemary - grated Parmesan cheese (optional) - extra-virgin olive oil"
104,9,Ragù,extra-virgin olive oil,NaN,N/A,False,"- 1 pound tubular dried pasta - 1 pound sweet Italian sausage - 1 onion, minced - 1 carrot, minced - 1 celery stalk, minced - 28oz (825 ml) can of whole tomatoes - 3 tablespoon of tomato paste - 1/4 cup fresh parsley - 1 sprig of fresh thyme - 1 sprig of fresh rosemary - grated Parmesan cheese (optional) - extra-virgin olive oil"
...,...,...,...,...,...,...,...
3095,357,Potato Soup,Onion Greens,NaN,N/A,True,"- Potatoes (yellow or brown), I don't count but 10+ - Butter, a stick or two - Whole Milk - Garlic - Cheese (optional) - Onion Greens (optional) - Sour Cream (optional)"
3096,357,Potato Soup,Sour Cream,NaN,N/A,True,"- Potatoes (yellow or brown), I don't count but 10+ - Butter, a stick or two - Whole Milk - Garlic - Cheese (optional) - Onion Greens (optional) - Sour Cream (optional)"
3102,359,Basic Sweet Potato Fries Recipe,Olive Oil,NaN,N/A,False,* 1-2 Sweet Pototoes (try different types) * Olive Oil * Cinnamon * Rosemary (optional)
3103,359,Basic Sweet Potato Fries Recipe,Cinnamon,NaN,N/A,False,* 1-2 Sweet Pototoes (try different types) * Olive Oil * Cinnamon * Rosemary (optional)
3104,359,Basic Sweet Potato Fries Recipe,Rosemary,NaN,N/A,True,* 1-2 Sweet Pototoes (try different types) * Olive Oil * Cinnamon * Rosemary (optional)

As for now, I'll map None and N/A units to "unit". 
Similarly, I'll map the missing quantities to 1 "unit".
And I'll add a marker to keep track of the concerned ingredients.

Besides, I'll map all the non-standard units to "unit" as well.

All of this will be done in the next notebook.

In [24]:
path_to_target_file = path_to_data / "output" / "3_standardize_the_data" / "flatten_parsed_recipes.csv"

In [25]:
df.to_csv(path_to_target_file)