# Standardize the data

## Reconstruction

In [1]:
import ast
import os
from pathlib import Path

import pandas as pd

In [2]:
path_to_data = Path(os.getcwd()).parents[1] / "data"
path_to_json = path_to_data / "output" / "3_standardize_the_data" / "transform.json"

In [3]:
df = pd.read_json(path_to_json)
df.head()

,id,title,serving_size,preparation_time,cooking_time,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max,date,tags,steps,ingredients_source_text,directions_source_text,ingredients.original_unit
0,0,Creamy Mashed Potatoes,4.0,None,None,1,potatoes,1.0,kg,False,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,kilogram
1,0,Creamy Mashed Potatoes,4.0,None,None,2,milk,0.2,l,False,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
2,0,Creamy Mashed Potatoes,4.0,None,None,3,mayonnaise,0.2,l,False,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
3,0,Creamy Mashed Potatoes,4.0,None,None,4,cheese,0.1,kg,True,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,gram
4,0,Creamy Mashed Potatoes,4.0,None,None,5,garlic powder,1.0,unit,True,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,None

In [4]:
# Define the columns to be included in the 'ingredient' dictionary
ingredient_columns = [
    'ingredients.id', 'ingredients.name', 'ingredients.quantity', 
    'ingredients.unit', 'ingredients.optional', "ingredients.original_unit",
    'ingredients.quantity.min', 'ingredients.quantity.max'
]

# Convert the selected columns to a dictionary with 'records' orientation
df['ingredient'] = df[ingredient_columns].rename(columns={
    'ingredients.id': 'id', 'ingredients.name': 'name', 
    'ingredients.quantity': 'quantity', 'ingredients.unit': 'unit',
    "ingredients.original_unit": "original_unit",
    'ingredients.optional': 'optional', 
    'ingredients.quantity.min': 'quantity_min', 
    'ingredients.quantity.max': 'quantity_max'
}).to_dict(orient='records')

# Display the first few rows of the updated DataFrame
df["ingredient"]

0       {'id': 1, 'name': 'potatoes', 'quantity': 1.0,...
1       {'id': 2, 'name': 'milk', 'quantity': 0.2, 'un...
2       {'id': 3, 'name': 'mayonnaise', 'quantity': 0....
3       {'id': 4, 'name': 'cheese', 'quantity': 0.1, '...
4       {'id': 5, 'name': 'garlic powder', 'quantity':...
                              ...
3100    {'id': 4, 'name': 'Marjoram', 'quantity': 1.0,...
3101    {'id': 1, 'name': 'Sweet Potatoes', 'quantity'...
3102    {'id': 2, 'name': 'Olive Oil', 'quantity': 1.0...
3103    {'id': 3, 'name': 'Cinnamon', 'quantity': 1.0,...
3104    {'id': 4, 'name': 'Rosemary', 'quantity': 1.0,...
Name: ingredient, Length: 3105, dtype: object

In [5]:
df.head()

,id,title,serving_size,preparation_time,cooking_time,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max,date,tags,steps,ingredients_source_text,directions_source_text,ingredients.original_unit,ingredient
0,0,Creamy Mashed Potatoes,4.0,None,None,1,potatoes,1.0,kg,False,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,kilogram,"{'id': 1, 'name': 'potatoes', 'quantity': 1.0,..."
1,0,Creamy Mashed Potatoes,4.0,None,None,2,milk,0.2,l,False,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml,"{'id': 2, 'name': 'milk', 'quantity': 0.2, 'un..."
2,0,Creamy Mashed Potatoes,4.0,None,None,3,mayonnaise,0.2,l,False,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml,"{'id': 3, 'name': 'mayonnaise', 'quantity': 0...."
3,0,Creamy Mashed Potatoes,4.0,None,None,4,cheese,0.1,kg,True,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,gram,"{'id': 4, 'name': 'cheese', 'quantity': 0.1, '..."
4,0,Creamy Mashed Potatoes,4.0,None,None,5,garlic powder,1.0,unit,True,NaN,NaN,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,None,"{'id': 5, 'name': 'garlic powder', 'quantity':..."

In [6]:
df = df.drop(columns=ingredient_columns)
df.head()

,id,title,serving_size,preparation_time,cooking_time,date,tags,steps,ingredients_source_text,directions_source_text,ingredient
0,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"{'id': 1, 'name': 'potatoes', 'quantity': 1.0,..."
1,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"{'id': 2, 'name': 'milk', 'quantity': 0.2, 'un..."
2,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"{'id': 3, 'name': 'mayonnaise', 'quantity': 0...."
3,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"{'id': 4, 'name': 'cheese', 'quantity': 0.1, '..."
4,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"{'id': 5, 'name': 'garlic powder', 'quantity':..."

In [7]:
# Group by all columns except 'ingredient' and aggregate 'ingredient' back into a list
agg_map = {col: 'first' for col in df.columns if col != 'ingredient'} | {'ingredient': list}

df_reverted = df.groupby("id", as_index=False, dropna=False).agg(agg_map)
df_reverted.head()

,id,title,serving_size,preparation_time,cooking_time,date,tags,steps,ingredients_source_text,directions_source_text,ingredient
0,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"[{'id': 1, 'name': 'potatoes', 'quantity': 1.0..."
1,1,Red Sauce (Ragu all'Italiana),7.0,12.0,None,2021-03-16,"[italian, sauce]","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...","[{'id': 1, 'name': 'salt pork', 'quantity': 0...."
2,2,Pancake,1.0,20.0,10.0,2021-03-11,"[quick, breakfast, sweet, pancake, cheesefare]","[{'number': 1, 'description': 'Mix all ingredi...",- 200g wheat flour or 100g glutenfree flour - ...,1. Mix all ingredients in a bowl. 2. Let the d...,"[{'id': 1, 'name': 'wheat flour', 'quantity': ..."
3,3,Teriyaki Beef Wok,2.0,10.0,15.0,2022-08-20,"[beef, asian, noodles]","[{'number': 1, 'description': 'Whisk water, co...",- 2 dL water - 2 tbsp cornstarch - 1 tbsp hone...,"1. Whisk water, cornstarch, honey, ginger and ...","[{'id': 1, 'name': 'water', 'quantity': 0.2, '..."
4,4,"Baked pasta with broccoli, boiled eggs and sca...",4.0,15.0,"{'min': 20.0, 'max': 30.0}",2021-04-15,"[italian, pasta, broccoli, cheesefare]","[{'number': 1, 'description': 'Boil water and ...",- 500g pasta - 500g broccoli - 4 eggs - 200g s...,1. Boil water and add salt (a handful for ever...,"[{'id': 1, 'name': 'pasta', 'quantity': 0.5, '..."

In [8]:
df_reverted.head()

,id,title,serving_size,preparation_time,cooking_time,date,tags,steps,ingredients_source_text,directions_source_text,ingredient
0,0,Creamy Mashed Potatoes,4.0,None,None,2021-03-12,"[potato, side, cheesefare]","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,"[{'id': 1, 'name': 'potatoes', 'quantity': 1.0..."
1,1,Red Sauce (Ragu all'Italiana),7.0,12.0,None,2021-03-16,"[italian, sauce]","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...","[{'id': 1, 'name': 'salt pork', 'quantity': 0...."
2,2,Pancake,1.0,20.0,10.0,2021-03-11,"[quick, breakfast, sweet, pancake, cheesefare]","[{'number': 1, 'description': 'Mix all ingredi...",- 200g wheat flour or 100g glutenfree flour - ...,1. Mix all ingredients in a bowl. 2. Let the d...,"[{'id': 1, 'name': 'wheat flour', 'quantity': ..."
3,3,Teriyaki Beef Wok,2.0,10.0,15.0,2022-08-20,"[beef, asian, noodles]","[{'number': 1, 'description': 'Whisk water, co...",- 2 dL water - 2 tbsp cornstarch - 1 tbsp hone...,"1. Whisk water, cornstarch, honey, ginger and ...","[{'id': 1, 'name': 'water', 'quantity': 0.2, '..."
4,4,"Baked pasta with broccoli, boiled eggs and sca...",4.0,15.0,"{'min': 20.0, 'max': 30.0}",2021-04-15,"[italian, pasta, broccoli, cheesefare]","[{'number': 1, 'description': 'Boil water and ...",- 500g pasta - 500g broccoli - 4 eggs - 200g s...,1. Boil water and add salt (a handful for ever...,"[{'id': 1, 'name': 'pasta', 'quantity': 0.5, '..."

In [9]:
df_reverted.rename(columns={"ingredient": "ingredients"}, inplace=True)

In [13]:
type(df_reverted.loc[0, "tags"][0])

str

In [10]:
#df_reverted["tags"] = df_reverted["tags"].apply(ast.literal_eval)
#df_reverted["steps"] = df_reverted["steps"].apply(ast.literal_eval)

ValueError: malformed node or string: ['potato', 'side', 'cheesefare']

In [14]:
path_to_output = path_to_data / "output" / "3_standardize_the_data" / "standardized_recipes.json"
df_reverted.to_json(path_to_output, orient='records', indent=4)