# Standardize the units

## Transformation

In [20]:
import os
from pathlib import Path

import pandas as pd
import numpy as np

In [21]:
path_to_data = Path(os.getcwd()).parents[1] / "data" 
path_to_recipes = path_to_data / "output" / "3_standardize_the_data" / "flatten_parsed_recipes.csv"

In [22]:
df = pd.read_csv(path_to_recipes)
df.head()

,id,title,serving_size,preparation_time,cooking_time,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max,date,tags,steps,ingredients_source_text,directions_source_text
0,0,Creamy Mashed Potatoes,4.0,NaN,NaN,1,potatoes,1.0,kilogram,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
1,0,Creamy Mashed Potatoes,4.0,NaN,NaN,2,milk,200.0,ml,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
2,0,Creamy Mashed Potatoes,4.0,NaN,NaN,3,mayonnaise,200.0,ml,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
3,0,Creamy Mashed Potatoes,4.0,NaN,NaN,4,cheese,100.0,gram,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...
4,0,Creamy Mashed Potatoes,4.0,NaN,NaN,5,garlic powder,NaN,NaN,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...

In [23]:
df.shape

(3105, 17)

In [24]:
# Saving the orignal unit for future reference

df["ingredients.original_unit"] = df["ingredients.unit"]

In [25]:
df["ingredients.original_unit"].unique().tolist()

['kilogram',
 'ml',
 'gram',
 nan,
 'strip',
 'unit',
 'pound',
 'clove',
 'tablespoon',
 'ounce',
 'teaspoon',
 'dl',
 'cup',
 'can',
 'sprig',
 'slice',
 'dash',
 'milliliter',
 'bunch',
 'splash',
 'handful',
 'head',
 'block',
 'stick',
 'unknown',
 'g',
 'leaf',
 'pinch',
 'bowl',
 'mug',
 'pint',
 'spoon',
 'package',
 'liter',
 'inch',
 'glass',
 'jar',
 'centiliter',
 'twig',
 'sheet',
 'piece',
 'rib',
 'cube',
 'handfull',
 'bottle',
 'serving',
 'fluid_ounce',
 'recipe',
 'cm',
 'container',
 'bag',
 'shot',
 'loaf',
 'envelope',
 'l',
 'medium',
 'large',
 'whole',
 'small',
 'percent',
 'pod',
 'fillet',
 'cl',
 'box',
 'quart',
 'strand',
 'stalk',
 'fruit']

### Mapping to standard units part I

In [26]:
units_map = {
    "kilogram": "kg",
    "ml": "ml",
    "gram": "g",
    np.nan: "unit",
    "strip": "unit",
    "unit": "unit",
    "pound": "pound",
    "clove": "unit",
    "tablespoon": "unit",
    "ounce": "unit",
    "teaspoon": "unit",
    "dl": "dl",
    "cup": "unit",
    "can": "unit",
    "sprig": "unit",
    "slice": "unit",
    "dash": "unit",
    "milliliter": "ml",
    "bunch": "unit",
    "splash": "unit",
    "handful": "unit",
    "head": "unit",
    "block": "unit",
    "stick": "unit",
    "unknown": "unit",
    "g": "g",
    "leaf": "unit",
    "pinch": "unit",
    "bowl": "unit",
    "mug": "unit",
    "pint": "unit",
    "spoon": "unit",
    "package": "unit",
    "liter": "l",
    "inch": "unit",
    "glass": "unit",
    "jar": "unit",
    "centiliter": "cl",
    "twig": "unit",
    "sheet": "unit",
    "piece": "unit",
    "rib": "unit",
    "cube": "unit",
    "handfull": "unit",
    "bottle": "unit",
    "serving": "unit",
    "fluid_ounce": "unit",
    "recipe": "unit",
    "cm": "cm",
    "container": "unit",
    "bag": "unit",
    "shot": "unit",
    "loaf": "unit",
    "envelope": "unit",
    "l": "l",
    "medium": "unit",
    "large": "unit",
    "whole": "unit",
    "small": "unit",
    "percent": "unit",
    "pod": "unit",
    "fillet": "unit",
    "cl": "cl",
    "box": "unit",
    "quart": "unit",
    "strand": "unit",
    "stalk": "unit",
    "fruit": "unit",
}

In [27]:
set(df["ingredients.original_unit"].unique().tolist()) == set(units_map.keys())

True

In [28]:
df["ingredients.unit"] = df["ingredients.unit"].replace(units_map)

In [29]:
df["ingredients.unit"].unique().tolist()

['kg', 'ml', 'g', 'unit', 'pound', 'dl', 'l', 'cl', 'cm']

In [30]:
# Conversion factors
conversion_factors = {
    "g": 0.001,  # grams to kilograms
    "ml": 0.001,  # milliliters to liters
    "cl": 0.01,  # centiliters to liters
    "dl": 0.1,  # deciliters to liters
    "pound": 0.453592,  # pounds to kilograms
    "cm": 1,  # centimeters to centimeters (no conversion needed)
    "l": 1,  # liters to liters (no conversion needed)
    "kg": 1,  # kilograms to kilograms (no conversion needed)
    "unit": 1,  # unit to unit (no conversion needed)
}

# Create a mapping for new units
new_units_map = {
    "g": "kg",
    "pound": "kg",
    "kg": "kg",
    "ml": "l",
    "cl": "l",
    "dl": "l",
    "l": "l",
    "cm": "cm",
    "unit": "unit",
}

# Replace quantities with converted quantities
df["ingredients.quantity"] = df["ingredients.quantity"] * df["ingredients.unit"].map(conversion_factors).fillna(1)
df["ingredients.quantity.min"] = df["ingredients.quantity.min"] * df["ingredients.unit"].map(conversion_factors).fillna(1)
df["ingredients.quantity.max"] = df["ingredients.quantity.max"] * df["ingredients.unit"].map(conversion_factors).fillna(1)

# Replace units with new units
df["ingredients.unit"] = df["ingredients.unit"].map(new_units_map).fillna(df["ingredients.unit"])

df.head()

,id,title,serving_size,preparation_time,cooking_time,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max,date,tags,steps,ingredients_source_text,directions_source_text,ingredients.original_unit
0,0,Creamy Mashed Potatoes,4.0,NaN,NaN,1,potatoes,1.0,kg,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,kilogram
1,0,Creamy Mashed Potatoes,4.0,NaN,NaN,2,milk,0.2,l,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
2,0,Creamy Mashed Potatoes,4.0,NaN,NaN,3,mayonnaise,0.2,l,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
3,0,Creamy Mashed Potatoes,4.0,NaN,NaN,4,cheese,0.1,kg,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,gram
4,0,Creamy Mashed Potatoes,4.0,NaN,NaN,5,garlic powder,NaN,unit,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,NaN

### Fixing the quantities

In [31]:
df[df["ingredients.quantity"].isna()].shape

(946, 18)

In [32]:
df[df["ingredients.quantity"].isna() & df["ingredients.quantity.min"].isna() & df["ingredients.quantity.max"].isna() ].shape

(807, 18)

In [33]:
df[df["ingredients.quantity"].isna() & df["ingredients.quantity.min"].isna() & df["ingredients.quantity.max"].isna() ][["id", "title", "ingredients.name", "ingredients.quantity", "ingredients.unit"]]

,id,title,ingredients.name,ingredients.quantity,ingredients.unit
4,0,Creamy Mashed Potatoes,garlic powder,NaN,unit
6,0,Creamy Mashed Potatoes,butter,NaN,unit
8,0,Creamy Mashed Potatoes,black pepper,NaN,unit
9,0,Creamy Mashed Potatoes,salt,NaN,unit
13,1,Red Sauce (Ragu all'Italiana),Crushed hot red pepper,NaN,unit
...,...,...,...,...,...
3099,358,Fried Anglerfish fillet,Chives or green onions,NaN,unit
3100,358,Fried Anglerfish fillet,Marjoram,NaN,unit
3102,359,Basic Sweet Potato Fries Recipe,Olive Oil,NaN,unit
3103,359,Basic Sweet Potato Fries Recipe,Cinnamon,NaN,unit
3104,359,Basic Sweet Potato Fries Recipe,Rosemary,NaN,unit

In [34]:
selector = (df["ingredients.quantity"].isna() & df["ingredients.quantity.min"].isna() & df["ingredients.quantity.max"].isna())
df.loc[selector, "ingredients.quantity"] = df.loc[selector, "ingredients.quantity"].fillna(1)
df.head()

,id,title,serving_size,preparation_time,cooking_time,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max,date,tags,steps,ingredients_source_text,directions_source_text,ingredients.original_unit
0,0,Creamy Mashed Potatoes,4.0,NaN,NaN,1,potatoes,1.0,kg,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,kilogram
1,0,Creamy Mashed Potatoes,4.0,NaN,NaN,2,milk,0.2,l,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
2,0,Creamy Mashed Potatoes,4.0,NaN,NaN,3,mayonnaise,0.2,l,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
3,0,Creamy Mashed Potatoes,4.0,NaN,NaN,4,cheese,0.1,kg,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,gram
4,0,Creamy Mashed Potatoes,4.0,NaN,NaN,5,garlic powder,1.0,unit,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,NaN

In [35]:
df.loc[df.loc[:, "ingredients.quantity"].isna(), ["id","title", "ingredients.name", "ingredients.quantity", "ingredients.unit", "ingredients.quantity.min", "ingredients.quantity.max"]]

,id,title,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.quantity.min,ingredients.quantity.max
5,0,Creamy Mashed Potatoes,bacon,NaN,unit,12.000000,16.00000
7,0,Creamy Mashed Potatoes,green onions,NaN,unit,3.000000,4.00000
63,6,Frijol con puerco,radishes,NaN,unit,8.000000,10.00000
114,11,Ragu Napoletano,San Marzano plum tomatoes,NaN,kg,2.721552,4.53592
118,11,Ragu Napoletano,red wine,NaN,unit,6.000000,8.00000
...,...,...,...,...,...,...,...
2922,337,Honey Sriracha Chicken Thighs,"bone-in, skin-on chicken thighs",NaN,unit,5.000000,6.00000
3020,347,'Kombucha',black (or green) tea,NaN,unit,3.000000,5.00000
3068,353,Drunken beans (Pintos Borrachos),pinto beans,NaN,unit,1.500000,1.50000
3080,355,Kvass,lemons,NaN,unit,1.000000,2.00000
3101,359,Basic Sweet Potato Fries Recipe,Sweet Potatoes,NaN,unit,1.000000,2.00000

In [36]:
df.loc[df.loc[:, "ingredients.quantity"].isna(), "ingredients.quantity"] = (df.loc[:, "ingredients.quantity.min"] + df.loc[:, "ingredients.quantity.max"]) / 2
df.loc[5,:]

id                                                                           0
title                                                   Creamy Mashed Potatoes
serving_size                                                               4.0
preparation_time                                                           NaN
cooking_time                                                               NaN
ingredients.id                                                               6
ingredients.name                                                         bacon
ingredients.quantity                                                      14.0
ingredients.unit                                                          unit
ingredients.optional                                                     False
ingredients.quantity.min                                                  12.0
ingredients.quantity.max                                                  16.0
date                                                                2021-03-12
tags                                          ['potato', 'side', 'cheesefare']
steps                        [{'number': 1, 'description': 'Peel and cut th...
ingredients_source_text      The quantities here are for about four adult p...
directions_source_text       1. Peel and cut the potatoes into medium sized...
ingredients.original_unit                                                strip
Name: 5, dtype: object

In [37]:
df.head(15)

,id,title,serving_size,preparation_time,cooking_time,ingredients.id,ingredients.name,ingredients.quantity,ingredients.unit,ingredients.optional,ingredients.quantity.min,ingredients.quantity.max,date,tags,steps,ingredients_source_text,directions_source_text,ingredients.original_unit
0,0,Creamy Mashed Potatoes,4.0,NaN,NaN,1,potatoes,1.000000,kg,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,kilogram
1,0,Creamy Mashed Potatoes,4.0,NaN,NaN,2,milk,0.200000,l,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
2,0,Creamy Mashed Potatoes,4.0,NaN,NaN,3,mayonnaise,0.200000,l,False,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,ml
3,0,Creamy Mashed Potatoes,4.0,NaN,NaN,4,cheese,0.100000,kg,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,gram
4,0,Creamy Mashed Potatoes,4.0,NaN,NaN,5,garlic powder,1.000000,unit,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,NaN
5,0,Creamy Mashed Potatoes,4.0,NaN,NaN,6,bacon,14.000000,unit,False,12.0,16.0,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,strip
6,0,Creamy Mashed Potatoes,4.0,NaN,NaN,7,butter,1.000000,unit,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,NaN
7,0,Creamy Mashed Potatoes,4.0,NaN,NaN,8,green onions,3.500000,unit,False,3.0,4.0,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,unit
8,0,Creamy Mashed Potatoes,4.0,NaN,NaN,9,black pepper,1.000000,unit,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,NaN
9,0,Creamy Mashed Potatoes,4.0,NaN,NaN,10,salt,1.000000,unit,True,NaN,NaN,2021-03-12,"['potato', 'side', 'cheesefare']","[{'number': 1, 'description': 'Peel and cut th...",The quantities here are for about four adult p...,1. Peel and cut the potatoes into medium sized...,NaN
10,1,Red Sauce (Ragu all'Italiana),7.0,12.0,NaN,1,salt pork,0.149685,kg,False,NaN,NaN,2021-03-16,"['italian', 'sauce']","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...",pound
11,1,Red Sauce (Ragu all'Italiana),7.0,12.0,NaN,2,chuck roast,0.907184,kg,False,NaN,NaN,2021-03-16,"['italian', 'sauce']","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...",pound
12,1,Red Sauce (Ragu all'Italiana),7.0,12.0,NaN,3,garlic,3.000000,unit,False,NaN,NaN,2021-03-16,"['italian', 'sauce']","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...",clove
13,1,Red Sauce (Ragu all'Italiana),7.0,12.0,NaN,4,Crushed hot red pepper,1.000000,unit,True,NaN,NaN,2021-03-16,"['italian', 'sauce']","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...",NaN
14,1,Red Sauce (Ragu all'Italiana),7.0,12.0,NaN,5,Sweet onion,1.000000,unit,False,NaN,NaN,2021-03-16,"['italian', 'sauce']","[{'number': 1, 'description': 'Mince the garli...",- 1/3 lb salt pork - 2 lb chuck roast - 3 Clov...,"1. Mince the garlic, peel the carrot, peel and...",unit

In [38]:
export_path = path_to_data / "output" / "3_standardize_the_data" / "standardized_recipes.csv"
df.to_csv(export_path, index=False)

Now the next step is to convert back the data to json.
This will be done in another notebook.